### ISSUE TITLE
TODO-List for Initial core.

### ISSUE THREAD

**Issue by SuperSaiyajinStackZ** [Universal-Team/LeafEdit-Core#1]
- [x] Add the SavWW, SavNL, SavWA & Sav class.
- [x]  Same for the Player.
- [x]  Same for the Villager.
- [x]  Same for the Town.
- [x] Add the Checksum ; StringUtils and EncryptedInt32 part.

And make the base class Virtual, so it can override.

After that is done continue with the other parts like Pattern ; Item and so on.

I will update this, when Progress has been made.

**Comment by SuperSaiyajinStackZ** [comment]
Update on this:

- SavWW ; SavNL & SavWA have been created.
- PlayerWW ; PlayerNL & PlayerWA have been created and a little bit of progress has been made.
- VillagerWW; VillagerNL & VillagerWA have been created and a little bit of progress has been made.

**Comment by SuperSaiyajinStackZ** [comment]
Ok, Interesting. AC:WW:

- Japanese Save Data seems to be `0x12224` for it instead of `0x15FDC`.

**Comment by SuperSaiyajinStackZ** [comment]
It also seems like the Offsets have changed completely(?) So a Research is needed for this!!

**Comment by SuperSaiyajinStackZ** [comment]
Ok checks for the Japanese Version & Checksum writing seems to work now. Now only the Data have to be RE'd.

**Comment by SuperSaiyajinStackZ** [comment]
Ok, most stuff is done now as of latest commit.

**Comment by SuperSaiyajinStackZ** [comment]
Updating this with the next work I plan:

- Work on the House | Room class.
- Work on the Item class to include the direction of the furniture in a House.
- Properly implement a way for the Item Filename defines.
- Research AC:WW Villagers more (specifically JPN & KOR).
- Finish Pattern Decode stuff and more research.

**Comment by SuperSaiyajinStackZ** [comment]
Closing this issue, cause that will be handled on the Project's side.
